### PR TITLE
Fire and forget

### PR DESCRIPTION
**Pull request by danielglauser**
Uses the fire-and-forget semantics for what was already a fire-and-forget call to `notification-works`. Also removes unused mentions of `scheduled-message-works`.

### CODE REVIEW

**Comment by cap10morgan** [comment]
@danielglauser Want to get this moving forward again?

**Comment by danielglauser** [comment]
Your timing is impeccable.

**Comment by danielglauser** [comment]
@cap10morgan Does anything upstream rely upon the information in the return? Ideally upstream services would no longer rely upon the return value.

**Comment by cap10morgan** [comment]
@danielglauser Which return value are you referring to?

**Comment by cap10morgan** [comment]
@danielglauser Can we get this one moving forward again too? Or close it if we no longer need it.

**Comment by danielglauser** [comment]
@cap10morgan The create handler, does the service calling that handler need a return value? All we would be able to pass back would be `{:status :ok}`.

**Pull request closed without merging**
