### PR TITLE
[EN] Add Immutant dependency and plugin

### PR DESCRIPTION
**Pull request by ericnormand**
Immutant/WildFly deployment is as simple as:

> lein immutant war -o /path/to/wildlfy

OR

> lein immutant war
> cp target/path-to-war.war /path/to/wildfly/standalone/deployments

I ran both of these and confirmed that they ran.

Documentation:

http://immutant.org/documentation/2.0.0-beta2/apidoc/guide-wildfly.html
http://immutant.org/documentation/2.0.0-beta2/apidoc/guide-installation.html

The org.immutant/immutant dependency is required to build the war.

### CODE REVIEW

**Comment by cap10morgan** [comment]
Simple as that, huh? And then the .war just executes the :main fn already specified in the project.clj?

Is there a smaller set of Immutant libs we can require for what we need?

**Comment by ericnormand** [comment]
It does run the main in the project.clj

I'm not sure I understand the question about similar immutant libs.

**Comment by cap10morgan** [comment]
So right now you're pulling in the "everything" Immutant namespace. That brings in every Immutant library (web, caching, queueing, etc.) and we're not using most of those. So I'm just wondering if we can require a subset of the namespaces and pare down the size of the .war some.

**Comment by ericnormand** [comment]
With a little digging: org.immutant/core is all you need.

**Comment by cap10morgan** [comment]
Great! LGTM.

**Comment by ericnormand** [comment]
https://www.pivotaltracker.com/story/show/90560158

**Pull request merged**
